site_name: BrazilCEP

repo_url: https://github.com/mstuttgart/brazilcep
repo_name: mstuttgart/brazilcep

edit_uri: tree/main/docs

theme:
  name: material
  palette:
    scheme: default
    primary: white
    accent: yellow
  logo: static/logo.png
  favicon: static/logo.png
  features:
    - content.code.copy

nav:
  - Home: "index.md"
  - "install.md"
  - "tutorial.md"
  - "migrate.md"
  - "CONTRIBUTING.md"
  - "CHANGELOG.md"

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
