---
name: Github CI Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install test dependencies
        run: |
          pip install -e ".[dev]"
          pip install ".[lint]"

      - name: Lint with pylint
        run: nox -s pylint
