---
name: Github CI Lint

on:
  push:
    branches:
      - main
      - develop

  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install test dependencies
        run: |
          pip install ".[dev]"

      - name: Lint with ruff
        run: make lint
